language: csharp
solution: shriek-fx.sln
mono: latest
dotnet: 2.0.0
dist: trusty
branches:
  only:
    - master
script:
 - dotnet restore 
 - dotnet build -r linux-x64 -f netstandard2.0
 - xbuild /p:Configuration=Release shriek-fx.sln /p:TargetFrameworkVersion="v4.6.1"